In [1]:
import pandas as pd
import numpy as np
from stargazer.stargazer import Stargazer
import statsmodels.api as sm

In [2]:
infr = pd.read_csv('infrast_data.csv', sep=';')
infr.what.unique()

array(['Traffic_light', '4-ways intersection', 'Curve', 'Road_immission',
       'Turn_left', 'Turn_right'], dtype=object)

In [3]:
infr

             what        lat       lon
0   Traffic_light  53.551073  9.970167
1   Traffic_light  53.550523  9.969615
2   Traffic_light  53.550082  9.969438
3   Traffic_light  53.546138  9.969437
4   Traffic_light  53.545436  9.972425
..            ...        ...       ...
72     Turn_right  53.552747  9.985368
73     Turn_right  53.557635  9.983789
74     Turn_right  53.557595  9.993096
75     Turn_right  53.557573  9.976766
76     Turn_right  53.553828  9.972632

[77 rows x 3 columns]

In [4]:
dist_v = pd.read_csv('distance_platoon.csv')
dist_v.head()

       PS_JC      JC_RW     RW_DW     DW_AA     AA_AK
0  23.255813  10.970501  3.916299  4.820478  5.776278
1  24.907458  10.970501  3.916299  4.820478  5.776278
2  28.401357  10.970501  3.916299  4.820478  5.776278
3  32.055915  10.970501  3.916299  4.820478  5.776278
4  37.266453  10.970501  3.916299  4.820478  5.776278

In [5]:
dist_coord = pd.read_csv('platoon_distances_coord.csv')
dist_coord.head()

,v1_lat,v1_lon,v2_lat,v2_lon,v3_lat,v3_lon,v4_lat,v4_lon,v5_lat,v5_lon
0,53.555853,9.972764,53.555833,9.972746,53.555815,9.972724,53.555801,9.972685,53.555775,9.972733
1,53.555853,9.972764,53.555833,9.972746,53.555815,9.972724,53.555801,9.972685,53.555775,9.972733
2,53.555858,9.972760,53.555842,9.972725,53.555815,9.972724,53.555801,9.972685,53.555775,9.972733
3,53.555858,9.972760,53.555842,9.972725,53.555815,9.972724,53.555801,9.972685,53.555775,9.972733
4,53.555853,9.972764,53.555833,9.972746,53.555815,9.972724,53.555801,9.972685,53.555775,9.972733

In [6]:
v1 = pd.read_csv('v1.csv')
v2 = pd.read_csv('v2.csv')
v3 = pd.read_csv('v3.csv')
v4 = pd.read_csv('v4.csv')
v5 = pd.read_csv('v5.csv')

In [7]:
v1 = v1.drop('Unnamed: 0',1)
v2 = v2.drop('Unnamed: 0',1)
v3 = v3.drop('Unnamed: 0',1)
v4 = v4.drop('Unnamed: 0',1)
v5 = v5.drop('Unnamed: 0',1)

C:\Users\marco\AppData\Local\Temp\ipykernel_17968\1394089028.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  v1 = v1.drop('Unnamed: 0',1)
C:\Users\marco\AppData\Local\Temp\ipykernel_17968\1394089028.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  v2 = v2.drop('Unnamed: 0',1)
C:\Users\marco\AppData\Local\Temp\ipykernel_17968\1394089028.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  v3 = v3.drop('Unnamed: 0',1)
C:\Users\marco\AppData\Local\Temp\ipykernel_17968\1394089028.py:4: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  v4 = v4.drop('Unnamed: 0',1)
C:\Users\marco\AppData\Local\Temp\ipykernel_17968\1394089028.py:5: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  v5 = v5.drop('Unnamed: 0',1)

In [8]:
v1.columns = infr.what
v2.columns = infr.what
v3.columns = infr.what
v4.columns = infr.what
v5.columns = infr.what

In [9]:
vlist = []
vlist.append(v1)
vlist.append(v2)
vlist.append(v3)
vlist.append(v4)
vlist.append(v5)

In [10]:
all_X = []
all_y = []

for k in range(len(vlist)):
    feats = []
    v = vlist[k]
    infrast = v.idxmin(axis=1)
    for i in range(len(v)):
        if (v.iloc[i][str(infrast[i])] < 80).any():
            feats.append([infrast[i]])
        else:
            feats.append([])
    new_v = pd.get_dummies(pd.DataFrame(feats), prefix='Feat')

    X = new_v.copy()
    y = dist_v[str(dist_v.columns[k])]
    X['old_dist'] = dist_v[str(dist_v.columns[k])].shift(10).fillna(0)
    all_X.append(X)
    all_y.append(y)

all_X_ = pd.concat(all_X).reset_index(drop=True).fillna(0)
all_y_ = pd.concat(all_y).reset_index(drop=True).fillna(0)
model_dist = sm.OLS(y, X).fit()
#predictions = model.predict(X)
model_dist.summary()

NameError: name 'sm' is not defined

In [ ]:
platoon_all_CO2_ = pd.read_csv('platoon_CO2.csv')

In [13]:
platoon_all_CO2_.head(2)

   PS_JC     JC_RW     RW_DW     DW_AA    AA_AK
0    0.0  0.004662  0.004662  0.001198  0.00233
1    0.0  0.004662  0.004662  0.001198  0.00233

In [14]:
all_X = []
all_y = []

for k in range(len(vlist)):
    feats = []
    v = vlist[k]
    infrast = v.idxmin(axis=1)
    for i in range(len(v)):
        if (v.iloc[i][str(infrast[i])] < 100).any():
            feats.append([infrast[i]])
        else:
            feats.append([])
    new_v = pd.get_dummies(pd.DataFrame(feats), prefix='Feat')

    X = new_v.copy()
    y = platoon_all_CO2_[str(platoon_all_CO2_.columns[k])]
    X['old_dist'] = dist_v[str(dist_v.columns[k])].shift(10).fillna(0)
    all_X.append(X)
    all_y.append(y)

all_X_ = pd.concat(all_X).reset_index(drop=True).fillna(0)
all_y_ = pd.concat(all_y).reset_index(drop=True).fillna(0)
model_co2 = sm.OLS(y, X).fit()
#predictions = model.predict(X)
model_co2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                  AA_AK   R-squared (uncentered):                   0.580
Model:                            OLS   Adj. R-squared (uncentered):              0.578
Method:                 Least Squares   F-statistic:                              257.0
Date:                Mon, 07 Aug 2023   Prob (F-statistic):                   2.99e-240
Time:                        09:28:27   Log-Likelihood:                          4970.4
No. Observations:                1310   AIC:                                     -9927.
Df Residuals:                    1303   BIC:                                     -9891.
Df Model:                           7
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
Feat_4-ways intersection     0.0084      0.001      6.303      0.000       0.006       0.011
Feat_Curve                   0.0049      0.001      5.426      0.000       0.003       0.007
Feat_Road_immission          0.0101      0.001      9.945      0.000       0.008       0.012
Feat_Traffic_light           0.0060      0.000     27.910      0.000       0.006       0.006
Feat_Turn_left               0.0045      0.003      1.636      0.102      -0.001       0.010
Feat_Turn_right              0.0088      0.001     16.529      0.000       0.008       0.010
old_dist                  3.843e-05   9.95e-06      3.862      0.000    1.89e-05    5.79e-05
==============================================================================
Omnibus:                      218.599   Durbin-Watson:                   0.086
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              404.560
Skew:                           1.017   Prob(JB):                     1.42e-88
Kurtosis:                       4.809   Cond. No.                         375.
==============================================================================

Notes:
[1] RÂ² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [15]:
stargazer = Stargazer([model_dist,model_co2])
#stargazer.custom_columns(ts,[1]*len(ts))
stargazer.show_model_numbers(False)
stargazer.show_degrees_of_freedom(False)
with open('../latex/1.tex','w') as f:
    f.write(stargazer.render_latex())
stargazer